name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Get Node.js Version
        run: |
          echo "$(cat ./package.json)" | jq .engines.node | xargs -I {} echo "NodeVersion="{} >> $GITHUB_ENV
      - name: Use Node.js ${{ env.NodeVersion }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.NodeVersion }}
          cache: 'npm'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --ignore-engines # will run `yarn install` command
      - name: Check Prettier
        run: yarn run prettier
      - name: Check ESLint
        run: yarn run lint
      - name: LWC Unit Tests
        run: yarn run test:unit
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

