name: node

on:
  workflow_call:

jobs:
  build:
    name: Select Node Version
    runs-on: ubuntu-latest
    steps:
      - name: Get Node.js Version
        run: |
          echo "$(cat ./package.json)" | jq .engines.node | xargs -I {} echo "NodeVersion="{} >> $GITHUB_ENV
      - name: Use Node.js ${{ env.NodeVersion }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.NodeVersion }}
          cache: 'npm'
